# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=50)),
                ('audio_duration', models.DurationField()),
                ('audio_size', models.IntegerField()),
                ('dwd_date_last', models.DateField()),
                ('action', models.CharField(choices=[('in_process', 'In process'), ('convert', 'Convert'), ('download', 'Downloaded'), ('done', 'Done')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FB_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_size', models.IntegerField()),
                ('video_duration', models.DurationField()),
                ('video_name', models.CharField(max_length=50)),
            ],
        ),
    ]
